version = 1.1
path = u'/Applications/FileMaker/FileMaker Pro 11 Advanced/FileMaker Pro Advanced.app'

classes = \
[('application', 'capp'),
 ('window', 'cwin'),
 ('document', 'docu'),
 ('database', 'cDB '),
 ('table', 'cTBL'),
 ('FileMaker_script', 'cSCP'),
 ('layout', 'ctbl'),
 ('field', 'ccol'),
 ('record', 'crow'),
 ('cell', 'ccel'),
 ('repetition', 'cREP'),
 ('request', 'cRQT'),
 ('menu_item', 'cmen'),
 ('menu', 'cmnu')]

enums = \
[('table', 'TABL'),
 ('view', 'VIEW'),
 ('read_only', 'nmod'),
 ('formulas_protected', 'fpro'),
 ('read_write', 'modf'),
 ('no_access', '\x00\x00\x00\x00'),
 ('read', '\x00\x00\x00\x01'),
 ('write', '\x00\x00\x00\x02'),
 ('update', '\x00\x00\x00\x04'),
 ('create', '\x00\x00\x00\x08'),
 ('delete', '\x00\x00\x00\x10'),
 ('read_write', '\x00\x00\x00\x03'),
 ('read_update', '\x00\x00\x00\x05'),
 ('read_create', '\x00\x00\x00\t'),
 ('read_delete', '\x00\x00\x00\x11'),
 ('write_update', '\x00\x00\x00\x06'),
 ('write_create', '\x00\x00\x00\n'),
 ('write_delete', '\x00\x00\x00\x12'),
 ('update_create', '\x00\x00\x00\x0c'),
 ('update_delete', '\x00\x00\x00\x14'),
 ('write_delete', '\x00\x00\x00\x18'),
 ('read_write_update', '\x00\x00\x00\x07'),
 ('read_write_create', '\x00\x00\x00\x0b'),
 ('read_write_delete', '\x00\x00\x00\x13'),
 ('write_update_create', '\x00\x00\x00\x0e'),
 ('write_update_delete', '\x00\x00\x00\x16'),
 ('update_create_delete', '\x00\x00\x00\x1c'),
 ('read_create_delete', '\x00\x00\x00\x19'),
 ('read_update_delete', '\x00\x00\x00\x15'),
 ('write_create_delete', '\x00\x00\x00\x1a'),
 ('read_update_create', '\x00\x00\x00\r'),
 ('no_delete', '\x00\x00\x00\x0f'),
 ('no_create', '\x00\x00\x00\x17'),
 ('no_update', '\x00\x00\x00\x1b'),
 ('no_read', '\x00\x00\x00\x1e'),
 ('no_write', '\x00\x00\x00\x1d'),
 ('full', '\x00\x00\x00\x1f'),
 ('ascending', '\x00\x00\x00\x00'),
 ('descending', '\x00\x00\x00\x01'),
 ('custom', '\x00\x00\x00\x04'),
 ('sum', 'TOTL'),
 ('count', 'CONT'),
 ('mean', 'MEAN'),
 ('standard_deviation', 'STDV'),
 ('average', 'AVRG'),
 ('minimum', 'MIN '),
 ('maximum', 'MAX '),
 ('unlocked', 'NOLK'),
 ('shared_lock', 'SHLK'),
 ('exclusive_lock', 'EXLK'),
 ('false', 'fals'),
 ('sharing_hidden', 'mltH'),
 ('true', 'true'),
 ('single', 'rSgl'),
 ('repeated', 'rFxd'),
 ('guest', 'pGST'),
 ('before_', 'befo'),
 ('after_', 'afte'),
 ('beginning_', 'bgng'),
 ('end_', 'end '),
 ('replace', 'rplc'),
 ('index', 'indx'),
 ('named', 'name'),
 ('ID_', 'ID  ')]

properties = \
[('best_type', 'pbst'),
 ('class_', 'pcls'),
 ('default_type', 'deft'),
 ('frontmost', 'pisf'),
 ('name', 'pnam'),
 ('version', 'vers'),
 ('bounds', 'pbnd'),
 ('visible', 'pvis'),
 ('index', 'pidx'),
 ('floating', 'isfl'),
 ('zoomable', 'iszm'),
 ('zoomed', 'pzum'),
 ('modal', 'pmod'),
 ('resizable', 'prsz'),
 ('has_close_box', 'hclb'),
 ('has_title_bar', 'ptit'),
 ('current_layout', 'pCLY'),
 ('current_record', 'pCRW'),
 ('current_table', 'pCTB'),
 ('current_cell', 'pCCL'),
 ('modified', 'imod'),
 ('multiuser', 'pMUr'),
 ('lock', 'pLCK'),
 ('access', 'pACS'),
 ('ID_', 'ID  '),
 ('protection', 'ppro'),
 ('kind', 'pKND'),
 ('choices', 'pCHS'),
 ('formula', 'pfor'),
 ('nulls_OK', 'pNLS'),
 ('repeats', 'pRPT'),
 ('repeat_size', 'pRPS'),
 ('unique_value', 'pUNQ'),
 ('globalValue', 'pGLL'),
 ('cellValue', 'vlue'),
 ('omitted', 'pOMT'),
 ('enabled', 'enbl'),
 ('item_number', 'itmn'),
 ('checked', 'pCHK')]

elements = \
[('applications', 'capp'),
 ('windows', 'cwin'),
 ('documents', 'docu'),
 ('databases', 'cDB '),
 ('tables', 'cTBL'),
 ('FileMaker_scripts', 'cSCP'),
 ('layouts', 'ctbl'),
 ('fields', 'ccol'),
 ('records', 'crow'),
 ('cells', 'ccel'),
 ('repetitions', 'cREP'),
 ('requests', 'cRQT'),
 ('menu_items', 'cmen'),
 ('menus', 'cmnu')]

commands = \
[('getURL', 'GURLGURL', [('for_accounts', 'pACT')]),
 ('exists', 'coredoex', []),
 ('show', 'miscmvis', []),
 ('close', 'coreclos', []),
 ('redo', 'miscredo', []),
 ('find', 'FMPRFIND', []),
 ('quit', 'aevtquit', []),
 ('cut', 'misccut ', []),
 ('get_remote_URL', 'FMPROPRM', []),
 ('open', 'aevtodoc', [('with_passwords', 'pPAS'), ('for_Accounts', 'pACT')]),
 ('create',
  'corecrel',
  [('new', 'kocl'),
   ('at', 'insh'),
   ('with_data', 'data'),
   ('with_properties', 'prdt')]),
 ('get_data', 'coregetd', [('as_', 'rtyp')]),
 ('event_info', 'coregtei', [('in_', 'wrcd')]),
 ('print_',
  'aevtpdoc',
  [('with_password', 'pPAS'),
   ('for_Accounts', 'pACT'),
   ('from_page', 'StPg'),
   ('to_page', 'NdPg'),
   ('with_copies', 'Cpis')]),
 ('duplicate', 'coreclon', [('to', 'insh')]),
 ('save', 'coresave', []),
 ('data_size', 'coredsiz', [('as_', 'rtyp')]),
 ('go_to', 'FMPRGOTO', []),
 ('sort', 'DATASORT', [('by', 'SRTE'), ('in_order', 'SRTT')]),
 ('undo', 'miscundo', []),
 ('set_data', 'coresetd', [('to', 'data')]),
 ('copy', 'misccopy', []),
 ('paste', 'miscpast', []),
 ('count', 'corecnte', [('class_', 'kocl')]),
 ('do_script', 'miscdosc', []),
 ('class_info', 'coreqobj', [('in_', 'wrcd')]),
 ('do_menu', 'miscmenu', [('menu_named', 'menn')]),
 ('delete', 'coredelo', [])]
